export default [
  {
    name: 'Rootbeer',
    shortDescription: 'Pedl cyc driver inj pick-up truck, pk-up/van in traf, init',
    description:
      'Pedal cycle driver injured in collision with car, pick-up truck or van in traffic accident, initial encounter',
    price: 403.6,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Automotive',
  },
  {
    name: 'Roe - Lump Fish, Black',
    shortDescription: 'Corrosion of cornea and conjunctival sac, unspecified eye',
    description: 'Corrosion of cornea and conjunctival sac, unspecified eye',
    price: 382.25,
    image: 'http://dummyimage.com/250x250.png/cc0000/ffffff',
    category: 'Health',
  },
  {
    name: 'Garam Marsala',
    shortDescription: 'Displ commnt fx shaft of unsp fibula, 7thQ',
    description:
      'Displaced comminuted fracture of shaft of unspecified fibula, subsequent encounter for open fracture type I or II with malunion',
    price: 466.82,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Automotive',
  },
  {
    name: 'Berry Brulee',
    shortDescription: 'Strain extensor musc/fasc/tend l rng fngr at forarm lv, init',
    description:
      'Strain of extensor muscle, fascia and tendon of left ring finger at forearm level, initial encounter',
    price: 486.52,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Computers',
  },
  {
    name: 'Coffee Cup 12oz 5342cd',
    shortDescription: 'Burn of 2nd deg mul sites of left wrist and hand, sequela',
    description:
      'Burn of second degree of multiple sites of left wrist and hand, sequela',
    price: 227.48,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Garden',
  },
  {
    name: 'Wine - Chianti Classica Docg',
    shortDescription: 'Wedge compression fracture of T11-T12 vertebra',
    description: 'Wedge compression fracture of T11-T12 vertebra',
    price: 412.23,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Grocery',
  },
  {
    name: 'Cheese - Gorgonzola',
    shortDescription: 'Other chronic allergic conjunctivitis',
    description: 'Other chronic allergic conjunctivitis',
    price: 468.72,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Clothing',
  },
  {
    name: 'Curry Paste - Green Masala',
    shortDescription: 'Laceration of radial artery at wrs/hnd lv of left arm, subs',
    description:
      'Laceration of radial artery at wrist and hand level of left arm, subsequent encounter',
    price: 235.68,
    image: 'http://dummyimage.com/250x250.png/cc0000/ffffff',
    category: 'Toys',
  },
  {
    name: 'Oil - Olive',
    shortDescription: 'Central corneal ulcer, bilateral',
    description: 'Central corneal ulcer, bilateral',
    price: 198.38,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Grocery',
  },
  {
    name: 'Sauce Tomato Pouch',
    shortDescription: 'Poisoning by sulfonamides, assault, sequela',
    description: 'Poisoning by sulfonamides, assault, sequela',
    price: 160.92,
    image: 'http://dummyimage.com/250x250.png/dddddd/000000',
    category: 'Automotive',
  },
  {
    name: 'Juice - Orange',
    shortDescription: 'Chronic embolism and thombos of deep veins of up extrem, bi',
    description:
      'Chronic embolism and thrombosis of deep veins of upper extremity, bilateral',
    price: 400.42,
    image: 'http://dummyimage.com/250x250.png/cc0000/ffffff',
    category: 'Music',
  },
  {
    name: 'Pheasants - Whole',
    shortDescription: 'Chondromalacia, left elbow',
    description: 'Chondromalacia, left elbow',
    price: 461.94,
    image: 'http://dummyimage.com/250x250.png/dddddd/000000',
    category: 'Grocery',
  },
  {
    name: 'Cheese - Cheddar With Claret',
    shortDescription: 'Crushing injury of penis, initial encounter',
    description: 'Crushing injury of penis, initial encounter',
    price: 343.59,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Shoes',
  },
  {
    name: 'Quail - Jumbo',
    shortDescription: 'Laceration w foreign body of unsp part of neck, init encntr',
    description:
      'Laceration with foreign body of unspecified part of neck, initial encounter',
    price: 341.69,
    image: 'http://dummyimage.com/250x250.png/dddddd/000000',
    category: 'Toys',
  },
  {
    name: 'Crab - Meat',
    shortDescription: 'Nondisp unsp fx right less toe(s), subs for fx w routn heal',
    description:
      'Nondisplaced unspecified fracture of right lesser toe(s), subsequent encounter for fracture with routine healing',
    price: 124.69,
    image: 'http://dummyimage.com/250x250.png/dddddd/000000',
    category: 'Kids',
  },
  {
    name: 'Venison - Striploin',
    shortDescription: 'Explosion and rupture of oth pressurized tire, pipe or hose',
    description: 'Explosion and rupture of other pressurized tire, pipe or hose',
    price: 335.15,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Health',
  },
  {
    name: 'Pie Shells 10',
    shortDescription: 'Path fx in neopltc dis, hip, unsp, subs for fx w routn heal',
    description:
      'Pathological fracture in neoplastic disease, hip, unspecified, subsequent encounter for fracture with routine healing',
    price: 232.36,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Grocery',
  },
  {
    name: 'Sugar Thermometer',
    shortDescription: 'Nondisp suprcndl fx w intrcndl extn low end l femr, 7thP',
    description:
      'Nondisplaced supracondylar fracture with intracondylar extension of lower end of left femur, subsequent encounter for closed fracture with malunion',
    price: 154.83,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Outdoors',
  },
  {
    name: 'Beef - Salted',
    shortDescription: 'Subluxation of unsp interphalangeal joint of l rng fngr',
    description: 'Subluxation of unspecified interphalangeal joint of left ring finger',
    price: 387.11,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Electronics',
  },
  {
    name: 'Aspic - Light',
    shortDescription: 'Toxic effect of dichloromethane, assault, sequela',
    description: 'Toxic effect of dichloromethane, assault, sequela',
    price: 109.23,
    image: 'http://dummyimage.com/250x250.png/dddddd/000000',
    category: 'Games',
  },
  {
    name: 'Nantucket - Kiwi Berry Cktl.',
    shortDescription: 'Blister (nonthermal), right lesser toe(s), sequela',
    description: 'Blister (nonthermal), right lesser toe(s), sequela',
    price: 432.12,
    image: 'http://dummyimage.com/250x250.png/dddddd/000000',
    category: 'Grocery',
  },
  {
    name: 'Basil - Primerba, Paste',
    shortDescription: 'Mech compl of femoral arterial graft (bypass)',
    description: 'Other mechanical complication of femoral arterial graft (bypass)',
    price: 365.28,
    image: 'http://dummyimage.com/250x250.png/cc0000/ffffff',
    category: 'Books',
  },
  {
    name: 'Cleaner - Comet',
    shortDescription: 'Open bite of unspecified finger with damage to nail, sequela',
    description: 'Open bite of unspecified finger with damage to nail, sequela',
    price: 266.32,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Toys',
  },
  {
    name: 'Mcguinness - Blue Curacao',
    shortDescription: 'Dislocation of unspecified internal joint prosthesis',
    description: 'Dislocation of unspecified internal joint prosthesis',
    price: 382.84,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Industrial',
  },
  {
    name: 'Gelatine Powder',
    shortDescription: 'Puncture wound with foreign body of unspecified ear, sequela',
    description: 'Puncture wound with foreign body of unspecified ear, sequela',
    price: 494.34,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Industrial',
  },
  {
    name: 'Wine - Niagara,vqa Reisling',
    shortDescription: 'Secondary lacrimal gland atrophy, unspecified lacrimal gland',
    description: 'Secondary lacrimal gland atrophy, unspecified lacrimal gland',
    price: 202.77,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Music',
  },
  {
    name: 'Taro Root',
    shortDescription: 'Contact with and (suspected) exposure to soil pollution',
    description: 'Contact with and (suspected) exposure to soil pollution',
    price: 368.84,
    image: 'http://dummyimage.com/250x250.png/dddddd/000000',
    category: 'Games',
  },
  {
    name: 'Table Cloth 62x120 Colour',
    shortDescription: 'Anterior subluxation of proximal end of tibia, right knee',
    description: 'Anterior subluxation of proximal end of tibia, right knee',
    price: 114.8,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Grocery',
  },
  {
    name: 'Coffee - Beans, Whole',
    shortDescription: 'Kaschin-Beck disease, left hand',
    description: 'Kaschin-Beck disease, left hand',
    price: 198.21,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Sports',
  },
  {
    name: 'Cocktail Napkin Blue',
    shortDescription: 'Other allergy, subsequent encounter',
    description: 'Other allergy, subsequent encounter',
    price: 441.01,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Health',
  },
  {
    name: 'Wine - Ruffino Chianti',
    shortDescription: 'Superficial injury of neck',
    description: 'Superficial injury of neck',
    price: 286.51,
    image: 'http://dummyimage.com/250x250.png/cc0000/ffffff',
    category: 'Tools',
  },
  {
    name: 'Star Anise, Whole',
    shortDescription: 'Lateral sublux of proximal end of tibia, right knee, init',
    description:
      'Lateral subluxation of proximal end of tibia, right knee, initial encounter',
    price: 257.99,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Books',
  },
  {
    name: 'Cheese - St. Andre',
    shortDescription: "Reiter's disease, multiple sites",
    description: "Reiter's disease, multiple sites",
    price: 257.55,
    image: 'http://dummyimage.com/250x250.png/dddddd/000000',
    category: 'Health',
  },
  {
    name: 'Gelatine Powder',
    shortDescription: 'Displaced spiral fracture of shaft of right femur, init',
    description:
      'Displaced spiral fracture of shaft of right femur, initial encounter for closed fracture',
    price: 187.78,
    image: 'http://dummyimage.com/250x250.png/cc0000/ffffff',
    category: 'Music',
  },
  {
    name: 'Bananas',
    shortDescription: 'Hemorrhage due to other internal prosth dev/grft, subs',
    description:
      'Hemorrhage due to other internal prosthetic devices, implants and grafts, subsequent encounter',
    price: 361.78,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Kids',
  },
  {
    name: 'Wine - Mondavi Coastal Private',
    shortDescription: 'Displ unsp condyle fx low end unsp femr, 7thB',
    description:
      'Displaced unspecified condyle fracture of lower end of unspecified femur, initial encounter for open fracture type I or II',
    price: 225.65,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Computers',
  },
  {
    name: 'Beef - Kobe Striploin',
    shortDescription: 'Poisoning by hemostatic drug, undetermined, subs encntr',
    description: 'Poisoning by hemostatic drug, undetermined, subsequent encounter',
    price: 494.14,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Industrial',
  },
  {
    name: 'Guava',
    shortDescription: 'Displ trimalleol fx r low leg, 7thE',
    description:
      'Displaced trimalleolar fracture of right lower leg, subsequent encounter for open fracture type I or II with routine healing',
    price: 327.49,
    image: 'http://dummyimage.com/250x250.png/cc0000/ffffff',
    category: 'Beauty',
  },
  {
    name: 'Cheese - Feta',
    shortDescription: 'Nondisp spiral fx shaft of r tibia, 7thD',
    description:
      'Nondisplaced spiral fracture of shaft of right tibia, subsequent encounter for closed fracture with routine healing',
    price: 228.04,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Books',
  },
  {
    name: 'Bag Clear 10 Lb',
    shortDescription: 'Nondisplaced fracture of unspecified tibial tuberosity',
    description: 'Nondisplaced fracture of unspecified tibial tuberosity',
    price: 392.19,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Books',
  },
  {
    name: 'Jolt Cola',
    shortDescription: 'Adhes due to fb acc left in body fol surgical op, init',
    description:
      'Adhesions due to foreign body accidentally left in body following surgical operation, initial encounter',
    price: 405.79,
    image: 'http://dummyimage.com/250x250.png/cc0000/ffffff',
    category: 'Automotive',
  },
  {
    name: 'Pepper - Pablano',
    shortDescription: 'Other injury of muscle and tendon of front wall of thorax',
    description: 'Other injury of muscle and tendon of front wall of thorax',
    price: 464.42,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Beauty',
  },
  {
    name: 'Oil - Canola',
    shortDescription: 'Deformity of orbit due to bone disease',
    description: 'Deformity of orbit due to bone disease',
    price: 118.81,
    image: 'http://dummyimage.com/250x250.png/cc0000/ffffff',
    category: 'Games',
  },
  {
    name: 'Pork - Ham Hocks - Smoked',
    shortDescription: 'Complete traumatic amputation of r forearm, level unsp, subs',
    description:
      'Complete traumatic amputation of right forearm, level unspecified, subsequent encounter',
    price: 173.72,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Jewelry',
  },
  {
    name: 'Cookies - Englishbay Oatmeal',
    shortDescription: 'Open bite of scrotum and testes, sequela',
    description: 'Open bite of scrotum and testes, sequela',
    price: 379.4,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Movies',
  },
  {
    name: 'Coffee - 10oz Cup 92961',
    shortDescription: 'Other superficial bite of right index finger',
    description: 'Other superficial bite of right index finger',
    price: 331.76,
    image: 'http://dummyimage.com/250x250.png/cc0000/ffffff',
    category: 'Home',
  },
  {
    name: 'Pears - Anjou',
    shortDescription: 'Strain of musc/tend at lower leg level, unsp leg, init',
    description:
      'Strain of other muscle(s) and tendon(s) at lower leg level, unspecified leg, initial encounter',
    price: 268.24,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Automotive',
  },
  {
    name: 'Honey - Comb',
    shortDescription: 'Disp fx of med malleolus of r tibia, 7thJ',
    description:
      'Displaced fracture of medial malleolus of right tibia, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing',
    price: 224.45,
    image: 'http://dummyimage.com/250x250.png/cc0000/ffffff',
    category: 'Toys',
  },
  {
    name: 'Noodles - Cellophane, Thin',
    shortDescription: 'Oth fx unsp lower leg, subs for clos fx w routn heal',
    description:
      'Other fracture of unspecified lower leg, subsequent encounter for closed fracture with routine healing',
    price: 311.2,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Computers',
  },
  {
    name: 'Dry Ice',
    shortDescription: 'Bursitis of left shoulder',
    description: 'Bursitis of left shoulder',
    price: 143.38,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Music',
  },
  {
    name: 'Appetizer - Spring Roll, Veg',
    shortDescription: 'Chronic multifocal osteomyelitis, ankle and foot',
    description: 'Chronic multifocal osteomyelitis, ankle and foot',
    price: 141.85,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Music',
  },
  {
    name: 'Wine - Blue Nun Qualitatswein',
    shortDescription: 'Obturator dislocation of unspecified hip, initial encounter',
    description: 'Obturator dislocation of unspecified hip, initial encounter',
    price: 409.84,
    image: 'http://dummyimage.com/250x250.png/dddddd/000000',
    category: 'Toys',
  },
  {
    name: 'Cafe Royale',
    shortDescription: 'Toxic effect of hydrogen sulfide, undetermined, sequela',
    description: 'Toxic effect of hydrogen sulfide, undetermined, sequela',
    price: 490.39,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Music',
  },
  {
    name: 'Oil - Sunflower',
    shortDescription: 'Malignant neoplasm of lower lobe, unsp bronchus or lung',
    description: 'Malignant neoplasm of lower lobe, unspecified bronchus or lung',
    price: 496.36,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Home',
  },
  {
    name: 'Tray - 12in Rnd Blk',
    shortDescription: "Monteggia's fx r ulna, 7thF",
    description:
      "Monteggia's fracture of right ulna, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with routine healing",
    price: 296.47,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Automotive',
  },
  {
    name: 'Tomatoes - Orange',
    shortDescription: 'Opioid dependence',
    description: 'Opioid dependence',
    price: 253.81,
    image: 'http://dummyimage.com/250x250.png/dddddd/000000',
    category: 'Beauty',
  },
  {
    name: 'Turkey - Breast, Smoked',
    shortDescription: 'Unsp fracture of skull, init encntr for closed fracture',
    description: 'Unspecified fracture of skull, initial encounter for closed fracture',
    price: 216.43,
    image: 'http://dummyimage.com/250x250.png/dddddd/000000',
    category: 'Games',
  },
  {
    name: 'Flavouring - Raspberry',
    shortDescription: 'Other reactive arthropathies, hip',
    description: 'Other reactive arthropathies, hip',
    price: 314.99,
    image: 'http://dummyimage.com/250x250.png/dddddd/000000',
    category: 'Clothing',
  },
  {
    name: 'Beer - Creemore',
    shortDescription: 'Corrosion of first degree of right knee, subs encntr',
    description: 'Corrosion of first degree of right knee, subsequent encounter',
    price: 174.26,
    image: 'http://dummyimage.com/250x250.png/dddddd/000000',
    category: 'Books',
  },
  {
    name: 'Fond - Neutral',
    shortDescription: 'Poisoning by unsp general anesthetics, intentional self-harm',
    description: 'Poisoning by unspecified general anesthetics, intentional self-harm',
    price: 181.68,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Garden',
  },
  {
    name: 'Pastry - Baked Cinnamon Stick',
    shortDescription: 'Nondisp spiral fx shaft of rad, r arm, 7thH',
    description:
      'Nondisplaced spiral fracture of shaft of radius, right arm, subsequent encounter for open fracture type I or II with delayed healing',
    price: 286.53,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Baby',
  },
  {
    name: 'Cheese - Brie, Triple Creme',
    shortDescription: 'Contus/lac cereb, w loss of consciousness of 31-59 min, subs',
    description:
      'Contusion and laceration of cerebrum, unspecified, with loss of consciousness of 31 minutes to 59 minutes, subsequent encounter',
    price: 362.52,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Shoes',
  },
  {
    name: 'Chocolate - Sugar Free Semi Choc',
    shortDescription: 'Stenosis of other vascular prosth dev/grft, subs',
    description:
      'Stenosis of other vascular prosthetic devices, implants and grafts, subsequent encounter',
    price: 158.88,
    image: 'http://dummyimage.com/250x250.png/cc0000/ffffff',
    category: 'Grocery',
  },
  {
    name: 'Lamb Rack Frenched Australian',
    shortDescription: 'Incomplete lesion of L5 level of lumbar spinal cord, subs',
    description:
      'Incomplete lesion of L5 level of lumbar spinal cord, subsequent encounter',
    price: 486.5,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Computers',
  },
  {
    name: 'Creamers - 10%',
    shortDescription: 'Fall (on)(from) sidewalk curb, subsequent encounter',
    description: 'Fall (on)(from) sidewalk curb, subsequent encounter',
    price: 241.39,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Sports',
  },
  {
    name: 'Grapes - Red',
    shortDescription: 'Oth nondisp fx of base of 1st MC bone, unsp hand, 7thP',
    description:
      'Other nondisplaced fracture of base of first metacarpal bone, unspecified hand, subsequent encounter for fracture with malunion',
    price: 272.61,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Clothing',
  },
  {
    name: 'Beef Striploin Aaa',
    shortDescription: 'Other secondary gout, unspecified elbow',
    description: 'Other secondary gout, unspecified elbow',
    price: 401.95,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Home',
  },
  {
    name: 'Wine - Red, Gamay Noir',
    shortDescription: 'Adverse effect of hydantoin derivatives',
    description: 'Adverse effect of hydantoin derivatives',
    price: 250.59,
    image: 'http://dummyimage.com/250x250.png/dddddd/000000',
    category: 'Books',
  },
  {
    name: 'Fib N9 - Prague Powder',
    shortDescription: 'Toxic effect of ketones, assault, subsequent encounter',
    description: 'Toxic effect of ketones, assault, subsequent encounter',
    price: 351.43,
    image: 'http://dummyimage.com/250x250.png/cc0000/ffffff',
    category: 'Kids',
  },
  {
    name: 'Pie Filling - Apple',
    shortDescription: 'Sickle-cell thalassemia with crisis',
    description: 'Sickle-cell thalassemia with crisis',
    price: 380.28,
    image: 'http://dummyimage.com/250x250.png/cc0000/ffffff',
    category: 'Computers',
  },
  {
    name: 'Salt - Kosher',
    shortDescription: 'Nondisp bicondylar fx r tibia, 7thJ',
    description:
      'Nondisplaced bicondylar fracture of right tibia, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing',
    price: 389.08,
    image: 'http://dummyimage.com/250x250.png/dddddd/000000',
    category: 'Home',
  },
  {
    name: 'Juice - Prune',
    shortDescription: 'Poisoning by amphetamines, undetermined, sequela',
    description: 'Poisoning by amphetamines, undetermined, sequela',
    price: 483.03,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Shoes',
  },
  {
    name: 'Teriyaki Sauce',
    shortDescription: 'Occupational exposure to risk factors',
    description: 'Occupational exposure to risk factors',
    price: 398.47,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Music',
  },
  {
    name: 'Flour - All Purpose',
    shortDescription: 'Unsp injury of musc/fasc/tend prt biceps, left arm, sequela',
    description:
      'Unspecified injury of muscle, fascia and tendon of other parts of biceps, left arm, sequela',
    price: 308.15,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Home',
  },
  {
    name: 'Tuna - Salad Premix',
    shortDescription: 'Injury of radial nerve at wrs/hnd lv of unsp arm, sequela',
    description:
      'Injury of radial nerve at wrist and hand level of unspecified arm, sequela',
    price: 172.79,
    image: 'http://dummyimage.com/250x250.png/cc0000/ffffff',
    category: 'Kids',
  },
  {
    name: 'Beans - Fine',
    shortDescription: 'Traumatic rupture of right radial collateral ligament, init',
    description:
      'Traumatic rupture of right radial collateral ligament, initial encounter',
    price: 273.2,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Garden',
  },
  {
    name: 'Chocolate - Sugar Free Semi Choc',
    shortDescription: 'Dislocation of distal interphalangeal joint of finger, init',
    description:
      'Dislocation of distal interphalangeal joint of other finger, initial encounter',
    price: 252.54,
    image: 'http://dummyimage.com/250x250.png/dddddd/000000',
    category: 'Books',
  },
  {
    name: 'Ice Cream Bar - Oreo Cone',
    shortDescription: 'Dislocation of unsp interphalangeal joint of finger, init',
    description:
      'Dislocation of unspecified interphalangeal joint of other finger, initial encounter',
    price: 470.16,
    image: 'http://dummyimage.com/250x250.png/cc0000/ffffff',
    category: 'Electronics',
  },
  {
    name: 'Coffee - Hazelnut Cream',
    shortDescription: 'Nondisp fx of med phalanx of r lit fngr, 7thG',
    description:
      'Nondisplaced fracture of medial phalanx of right little finger, subsequent encounter for fracture with delayed healing',
    price: 276.04,
    image: 'http://dummyimage.com/250x250.png/dddddd/000000',
    category: 'Health',
  },
  {
    name: 'Pepper - White, Whole',
    shortDescription: 'Twin pregnancy, monochorionic/diamniotic, first trimester',
    description: 'Twin pregnancy, monochorionic/diamniotic, first trimester',
    price: 454.95,
    image: 'http://dummyimage.com/250x250.png/cc0000/ffffff',
    category: 'Beauty',
  },
  {
    name: 'Cheese - Pont Couvert',
    shortDescription: 'Laceration w foreign body of left cheek and TMJ area',
    description: 'Laceration with foreign body of left cheek and temporomandibular area',
    price: 298.01,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Clothing',
  },
  {
    name: 'Muffin Mix - Morning Glory',
    shortDescription: 'Burn of first degree of back of unsp hand, subs encntr',
    description: 'Burn of first degree of back of unspecified hand, subsequent encounter',
    price: 138.13,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Sports',
  },
  {
    name: 'Sage - Ground',
    shortDescription: 'Oth injury of deep palmar arch of unsp hand, subs encntr',
    description:
      'Other specified injury of deep palmar arch of unspecified hand, subsequent encounter',
    price: 467.57,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Health',
  },
  {
    name: 'Juice - V8, Tomato',
    shortDescription: 'Lacerat less saphenous at lower leg level, left leg, subs',
    description:
      'Laceration of lesser saphenous vein at lower leg level, left leg, subsequent encounter',
    price: 202.8,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Tools',
  },
  {
    name: 'Apple - Fuji',
    shortDescription: 'Underdosing of unspecified systemic antibiotic, init encntr',
    description: 'Underdosing of unspecified systemic antibiotic, initial encounter',
    price: 323.16,
    image: 'http://dummyimage.com/250x250.png/cc0000/ffffff',
    category: 'Movies',
  },
  {
    name: 'Lamb - Sausage Casings',
    shortDescription: 'Other articular cartilage disorders, hand',
    description: 'Other articular cartilage disorders, hand',
    price: 125.79,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Grocery',
  },
  {
    name: 'Wine - Chardonnay South',
    shortDescription: 'Disorder of amnio fluid and membrns, unsp, unsp tri, fetus 1',
    description:
      'Disorder of amniotic fluid and membranes, unspecified, unspecified trimester, fetus 1',
    price: 115.0,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Jewelry',
  },
  {
    name: 'French Pastry - Mini Chocolate',
    shortDescription: 'Fracture of unsp phalanx of r mid finger, init for opn fx',
    description:
      'Fracture of unspecified phalanx of right middle finger, initial encounter for open fracture',
    price: 415.23,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Grocery',
  },
  {
    name: 'Chestnuts - Whole,canned',
    shortDescription: 'Other superficial bite of hand',
    description: 'Other superficial bite of hand',
    price: 174.52,
    image: 'http://dummyimage.com/250x250.png/cc0000/ffffff',
    category: 'Music',
  },
  {
    name: 'Nut - Macadamia',
    shortDescription: 'Osteonecrosis in diseases classified elsewhere, unsp hand',
    description: 'Osteonecrosis in diseases classified elsewhere, unspecified hand',
    price: 221.22,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Outdoors',
  },
  {
    name: 'Energy Drink Bawls',
    shortDescription: 'Injury of unspecified cranial nerve, initial encounter',
    description: 'Injury of unspecified cranial nerve, initial encounter',
    price: 115.47,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Garden',
  },
  {
    name: 'Magnotta Bel Paese Red',
    shortDescription: 'Oth soft tissue disorders related to use/pressure of thigh',
    description:
      'Other soft tissue disorders related to use, overuse and pressure of thigh',
    price: 192.8,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Outdoors',
  },
  {
    name: 'Pears - Bosc',
    shortDescription: 'Alcoholic cardiomyopathy',
    description: 'Alcoholic cardiomyopathy',
    price: 319.88,
    image: 'http://dummyimage.com/250x250.png/dddddd/000000',
    category: 'Movies',
  },
  {
    name: 'Beef Flat Iron Steak',
    shortDescription: 'Inj l int crtd,intcr w LOC w dth d/t brain inj bf consc,sqla',
    description:
      'Injury of left internal carotid artery, intracranial portion, not elsewhere classified with loss of consciousness of any duration with death due to brain injury prior to regaining consciousness, sequela',
    price: 338.61,
    image: 'http://dummyimage.com/250x250.png/cc0000/ffffff',
    category: 'Beauty',
  },
  {
    name: 'Brocolinni - Gaylan, Chinese',
    shortDescription: 'Legal intervnt w oth blunt obj, law enforc offl inj, sequela',
    description:
      'Legal intervention involving other blunt objects, law enforcement official injured, sequela',
    price: 118.4,
    image: 'http://dummyimage.com/250x250.png/cc0000/ffffff',
    category: 'Electronics',
  },
  {
    name: 'Pickle - Dill',
    shortDescription: 'Melanoma in situ of anal skin',
    description: 'Melanoma in situ of anal skin',
    price: 149.91,
    image: 'http://dummyimage.com/250x250.png/dddddd/000000',
    category: 'Movies',
  },
  {
    name: 'Shrimp - Tiger 21/25',
    shortDescription: 'Diagnostic and monitoring cardiovasc devices assoc w incdt',
    description:
      'Diagnostic and monitoring cardiovascular devices associated with adverse incidents',
    price: 231.31,
    image: 'http://dummyimage.com/250x250.png/cc0000/ffffff',
    category: 'Beauty',
  },
  {
    name: 'Veal - Osso Bucco',
    shortDescription: 'Nondisp fx of med malleolus of l tibia, 7thE',
    description:
      'Nondisplaced fracture of medial malleolus of left tibia, subsequent encounter for open fracture type I or II with routine healing',
    price: 410.6,
    image: 'http://dummyimage.com/250x250.png/cc0000/ffffff',
    category: 'Clothing',
  },
  {
    name: 'Stock - Veal, Brown',
    shortDescription: 'Fall down embankment (hill), subsequent encounter',
    description: 'Fall down embankment (hill), subsequent encounter',
    price: 284.5,
    image: 'http://dummyimage.com/250x250.png/ff4444/ffffff',
    category: 'Grocery',
  },
  {
    name: 'Trout - Rainbow, Frozen',
    shortDescription: 'Breakdown of int fix of unsp bone of limb, sequela',
    description:
      'Breakdown (mechanical) of internal fixation device of unspecified bone of limb, sequela',
    price: 108.7,
    image: 'http://dummyimage.com/250x250.png/5fa2dd/ffffff',
    category: 'Music',
  },
];
